services:
  books:
    container_name: books
    command: sh -c "/app/migrator & /app/books wait"
    depends_on:
     - books-db
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - CONFIG_PATH=./config/local.yaml
    volumes:
      - ./config:/app/config:ro
      - ./migrations:/app/migrations:ro
    networks:
      - books_net
      - shared
    ports:
      - 40004:40004

  books-db:
    image: postgres:15
    container_name: books-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - books_net
      - shared
volumes:
  postgres_data:
networks:
  books_net:
  shared:
   external: true