# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import students_pb2 as students__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in students_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StudentsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateStudent = channel.unary_unary(
                '/students.StudentsService/CreateStudent',
                request_serializer=students__pb2.CreateStudentRequest.SerializeToString,
                response_deserializer=students__pb2.CreateStudentResponse.FromString,
                _registered_method=True)
        self.DeleteStudentByID = channel.unary_unary(
                '/students.StudentsService/DeleteStudentByID',
                request_serializer=students__pb2.DeleteStudentByIDRequest.SerializeToString,
                response_deserializer=students__pb2.DeleteStudentByIDResponse.FromString,
                _registered_method=True)
        self.UpdateFullNameOfStudent = channel.unary_unary(
                '/students.StudentsService/UpdateFullNameOfStudent',
                request_serializer=students__pb2.UpdateFullNameOfStudentRequest.SerializeToString,
                response_deserializer=students__pb2.UpdateFullNameOfStudentResponse.FromString,
                _registered_method=True)
        self.UpdateGradeOfStudent = channel.unary_unary(
                '/students.StudentsService/UpdateGradeOfStudent',
                request_serializer=students__pb2.UpdateGradeOfStudentRequest.SerializeToString,
                response_deserializer=students__pb2.UpdateGradeOfStudentResponse.FromString,
                _registered_method=True)
        self.UpdateLetterOfStudent = channel.unary_unary(
                '/students.StudentsService/UpdateLetterOfStudent',
                request_serializer=students__pb2.UpdateLetterOfStudentRequest.SerializeToString,
                response_deserializer=students__pb2.UpdateLetterOfStudentResponse.FromString,
                _registered_method=True)
        self.GetStudentByID = channel.unary_unary(
                '/students.StudentsService/GetStudentByID',
                request_serializer=students__pb2.GetStudentByIDRequest.SerializeToString,
                response_deserializer=students__pb2.GetStudentByIDResponse.FromString,
                _registered_method=True)
        self.GetStudentByFullName = channel.unary_unary(
                '/students.StudentsService/GetStudentByFullName',
                request_serializer=students__pb2.GetStudentByFullNameRequest.SerializeToString,
                response_deserializer=students__pb2.GetStudentByFullNameResponse.FromString,
                _registered_method=True)
        self.GetGrade = channel.unary_unary(
                '/students.StudentsService/GetGrade',
                request_serializer=students__pb2.GetGradeRequest.SerializeToString,
                response_deserializer=students__pb2.GetGradeResponse.FromString,
                _registered_method=True)
        self.GetParallel = channel.unary_unary(
                '/students.StudentsService/GetParallel',
                request_serializer=students__pb2.GetParallelRequest.SerializeToString,
                response_deserializer=students__pb2.GetParallelResponse.FromString,
                _registered_method=True)
        self.GetStudentStats = channel.unary_unary(
                '/students.StudentsService/GetStudentStats',
                request_serializer=students__pb2.GetStudentStatsRequest.SerializeToString,
                response_deserializer=students__pb2.GetStudentStatsResponse.FromString,
                _registered_method=True)


class StudentsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateStudent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteStudentByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFullNameOfStudent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateGradeOfStudent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateLetterOfStudent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStudentByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStudentByFullName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGrade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetParallel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStudentStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StudentsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateStudent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateStudent,
                    request_deserializer=students__pb2.CreateStudentRequest.FromString,
                    response_serializer=students__pb2.CreateStudentResponse.SerializeToString,
            ),
            'DeleteStudentByID': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteStudentByID,
                    request_deserializer=students__pb2.DeleteStudentByIDRequest.FromString,
                    response_serializer=students__pb2.DeleteStudentByIDResponse.SerializeToString,
            ),
            'UpdateFullNameOfStudent': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFullNameOfStudent,
                    request_deserializer=students__pb2.UpdateFullNameOfStudentRequest.FromString,
                    response_serializer=students__pb2.UpdateFullNameOfStudentResponse.SerializeToString,
            ),
            'UpdateGradeOfStudent': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateGradeOfStudent,
                    request_deserializer=students__pb2.UpdateGradeOfStudentRequest.FromString,
                    response_serializer=students__pb2.UpdateGradeOfStudentResponse.SerializeToString,
            ),
            'UpdateLetterOfStudent': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLetterOfStudent,
                    request_deserializer=students__pb2.UpdateLetterOfStudentRequest.FromString,
                    response_serializer=students__pb2.UpdateLetterOfStudentResponse.SerializeToString,
            ),
            'GetStudentByID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStudentByID,
                    request_deserializer=students__pb2.GetStudentByIDRequest.FromString,
                    response_serializer=students__pb2.GetStudentByIDResponse.SerializeToString,
            ),
            'GetStudentByFullName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStudentByFullName,
                    request_deserializer=students__pb2.GetStudentByFullNameRequest.FromString,
                    response_serializer=students__pb2.GetStudentByFullNameResponse.SerializeToString,
            ),
            'GetGrade': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGrade,
                    request_deserializer=students__pb2.GetGradeRequest.FromString,
                    response_serializer=students__pb2.GetGradeResponse.SerializeToString,
            ),
            'GetParallel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParallel,
                    request_deserializer=students__pb2.GetParallelRequest.FromString,
                    response_serializer=students__pb2.GetParallelResponse.SerializeToString,
            ),
            'GetStudentStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStudentStats,
                    request_deserializer=students__pb2.GetStudentStatsRequest.FromString,
                    response_serializer=students__pb2.GetStudentStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'students.StudentsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('students.StudentsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StudentsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateStudent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/students.StudentsService/CreateStudent',
            students__pb2.CreateStudentRequest.SerializeToString,
            students__pb2.CreateStudentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteStudentByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/students.StudentsService/DeleteStudentByID',
            students__pb2.DeleteStudentByIDRequest.SerializeToString,
            students__pb2.DeleteStudentByIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateFullNameOfStudent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/students.StudentsService/UpdateFullNameOfStudent',
            students__pb2.UpdateFullNameOfStudentRequest.SerializeToString,
            students__pb2.UpdateFullNameOfStudentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateGradeOfStudent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/students.StudentsService/UpdateGradeOfStudent',
            students__pb2.UpdateGradeOfStudentRequest.SerializeToString,
            students__pb2.UpdateGradeOfStudentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateLetterOfStudent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/students.StudentsService/UpdateLetterOfStudent',
            students__pb2.UpdateLetterOfStudentRequest.SerializeToString,
            students__pb2.UpdateLetterOfStudentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStudentByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/students.StudentsService/GetStudentByID',
            students__pb2.GetStudentByIDRequest.SerializeToString,
            students__pb2.GetStudentByIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStudentByFullName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/students.StudentsService/GetStudentByFullName',
            students__pb2.GetStudentByFullNameRequest.SerializeToString,
            students__pb2.GetStudentByFullNameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGrade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/students.StudentsService/GetGrade',
            students__pb2.GetGradeRequest.SerializeToString,
            students__pb2.GetGradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetParallel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/students.StudentsService/GetParallel',
            students__pb2.GetParallelRequest.SerializeToString,
            students__pb2.GetParallelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStudentStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/students.StudentsService/GetStudentStats',
            students__pb2.GetStudentStatsRequest.SerializeToString,
            students__pb2.GetStudentStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
