# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import books_pb2 as books__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in books_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BooksStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddBook = channel.unary_unary(
                '/books.Books/AddBook',
                request_serializer=books__pb2.AddBookRequest.SerializeToString,
                response_deserializer=books__pb2.AddBookResponse.FromString,
                _registered_method=True)
        self.TakeBook = channel.unary_unary(
                '/books.Books/TakeBook',
                request_serializer=books__pb2.TakeBookRequest.SerializeToString,
                response_deserializer=books__pb2.TakeBookResponse.FromString,
                _registered_method=True)
        self.GetBookByID = channel.unary_unary(
                '/books.Books/GetBookByID',
                request_serializer=books__pb2.GetBookByIDRequest.SerializeToString,
                response_deserializer=books__pb2.GetBookByIDResponse.FromString,
                _registered_method=True)
        self.GetBookByTitle = channel.unary_unary(
                '/books.Books/GetBookByTitle',
                request_serializer=books__pb2.GetBookByTitleRequest.SerializeToString,
                response_deserializer=books__pb2.GetBookByTitleResponse.FromString,
                _registered_method=True)
        self.DeleteBook = channel.unary_unary(
                '/books.Books/DeleteBook',
                request_serializer=books__pb2.DeleteBookRequest.SerializeToString,
                response_deserializer=books__pb2.DeleteBookResponse.FromString,
                _registered_method=True)
        self.AddCopies = channel.unary_unary(
                '/books.Books/AddCopies',
                request_serializer=books__pb2.AddCopiesRequest.SerializeToString,
                response_deserializer=books__pb2.AddCopiesResponse.FromString,
                _registered_method=True)
        self.GetListOfBooks = channel.unary_unary(
                '/books.Books/GetListOfBooks',
                request_serializer=books__pb2.GetListOfBooksRequest.SerializeToString,
                response_deserializer=books__pb2.GetListOfBooksResponse.FromString,
                _registered_method=True)
        self.FilterBooksByGenreList = channel.unary_unary(
                '/books.Books/FilterBooksByGenreList',
                request_serializer=books__pb2.FilterBooksByGenreListRequest.SerializeToString,
                response_deserializer=books__pb2.FilterBooksByGenreListResponse.FromString,
                _registered_method=True)


class BooksServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TakeBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBookByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBookByTitle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddCopies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetListOfBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FilterBooksByGenreList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BooksServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddBook': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBook,
                    request_deserializer=books__pb2.AddBookRequest.FromString,
                    response_serializer=books__pb2.AddBookResponse.SerializeToString,
            ),
            'TakeBook': grpc.unary_unary_rpc_method_handler(
                    servicer.TakeBook,
                    request_deserializer=books__pb2.TakeBookRequest.FromString,
                    response_serializer=books__pb2.TakeBookResponse.SerializeToString,
            ),
            'GetBookByID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookByID,
                    request_deserializer=books__pb2.GetBookByIDRequest.FromString,
                    response_serializer=books__pb2.GetBookByIDResponse.SerializeToString,
            ),
            'GetBookByTitle': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookByTitle,
                    request_deserializer=books__pb2.GetBookByTitleRequest.FromString,
                    response_serializer=books__pb2.GetBookByTitleResponse.SerializeToString,
            ),
            'DeleteBook': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBook,
                    request_deserializer=books__pb2.DeleteBookRequest.FromString,
                    response_serializer=books__pb2.DeleteBookResponse.SerializeToString,
            ),
            'AddCopies': grpc.unary_unary_rpc_method_handler(
                    servicer.AddCopies,
                    request_deserializer=books__pb2.AddCopiesRequest.FromString,
                    response_serializer=books__pb2.AddCopiesResponse.SerializeToString,
            ),
            'GetListOfBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetListOfBooks,
                    request_deserializer=books__pb2.GetListOfBooksRequest.FromString,
                    response_serializer=books__pb2.GetListOfBooksResponse.SerializeToString,
            ),
            'FilterBooksByGenreList': grpc.unary_unary_rpc_method_handler(
                    servicer.FilterBooksByGenreList,
                    request_deserializer=books__pb2.FilterBooksByGenreListRequest.FromString,
                    response_serializer=books__pb2.FilterBooksByGenreListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'books.Books', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('books.Books', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Books(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/books.Books/AddBook',
            books__pb2.AddBookRequest.SerializeToString,
            books__pb2.AddBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TakeBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/books.Books/TakeBook',
            books__pb2.TakeBookRequest.SerializeToString,
            books__pb2.TakeBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBookByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/books.Books/GetBookByID',
            books__pb2.GetBookByIDRequest.SerializeToString,
            books__pb2.GetBookByIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBookByTitle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/books.Books/GetBookByTitle',
            books__pb2.GetBookByTitleRequest.SerializeToString,
            books__pb2.GetBookByTitleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/books.Books/DeleteBook',
            books__pb2.DeleteBookRequest.SerializeToString,
            books__pb2.DeleteBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddCopies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/books.Books/AddCopies',
            books__pb2.AddCopiesRequest.SerializeToString,
            books__pb2.AddCopiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetListOfBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/books.Books/GetListOfBooks',
            books__pb2.GetListOfBooksRequest.SerializeToString,
            books__pb2.GetListOfBooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FilterBooksByGenreList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/books.Books/FilterBooksByGenreList',
            books__pb2.FilterBooksByGenreListRequest.SerializeToString,
            books__pb2.FilterBooksByGenreListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
