# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import issue_pb2 as issue__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in issue_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IssueServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IssueBook = channel.unary_unary(
                '/issue.IssueService/IssueBook',
                request_serializer=issue__pb2.IssueRequest.SerializeToString,
                response_deserializer=issue__pb2.IssueResponse.FromString,
                _registered_method=True)
        self.CheckAvailability = channel.unary_unary(
                '/issue.IssueService/CheckAvailability',
                request_serializer=issue__pb2.CheckAvailabilityRequest.SerializeToString,
                response_deserializer=issue__pb2.CheckAvailabilityResponse.FromString,
                _registered_method=True)
        self.ReturnBook = channel.unary_unary(
                '/issue.IssueService/ReturnBook',
                request_serializer=issue__pb2.ReturnRequest.SerializeToString,
                response_deserializer=issue__pb2.ReturnResponse.FromString,
                _registered_method=True)
        self.ReportLost = channel.unary_unary(
                '/issue.IssueService/ReportLost',
                request_serializer=issue__pb2.ReportLostRequest.SerializeToString,
                response_deserializer=issue__pb2.ReportLostResponse.FromString,
                _registered_method=True)
        self.GetAllDebts = channel.unary_unary(
                '/issue.IssueService/GetAllDebts',
                request_serializer=issue__pb2.GetAllDebtsRequest.SerializeToString,
                response_deserializer=issue__pb2.GetAllDebtsResponse.FromString,
                _registered_method=True)
        self.ViewDebtors = channel.unary_unary(
                '/issue.IssueService/ViewDebtors',
                request_serializer=issue__pb2.ViewDebtorsRequest.SerializeToString,
                response_deserializer=issue__pb2.ViewDebtorsResponse.FromString,
                _registered_method=True)


class IssueServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IssueBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckAvailability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportLost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllDebts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewDebtors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IssueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IssueBook': grpc.unary_unary_rpc_method_handler(
                    servicer.IssueBook,
                    request_deserializer=issue__pb2.IssueRequest.FromString,
                    response_serializer=issue__pb2.IssueResponse.SerializeToString,
            ),
            'CheckAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAvailability,
                    request_deserializer=issue__pb2.CheckAvailabilityRequest.FromString,
                    response_serializer=issue__pb2.CheckAvailabilityResponse.SerializeToString,
            ),
            'ReturnBook': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnBook,
                    request_deserializer=issue__pb2.ReturnRequest.FromString,
                    response_serializer=issue__pb2.ReturnResponse.SerializeToString,
            ),
            'ReportLost': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportLost,
                    request_deserializer=issue__pb2.ReportLostRequest.FromString,
                    response_serializer=issue__pb2.ReportLostResponse.SerializeToString,
            ),
            'GetAllDebts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllDebts,
                    request_deserializer=issue__pb2.GetAllDebtsRequest.FromString,
                    response_serializer=issue__pb2.GetAllDebtsResponse.SerializeToString,
            ),
            'ViewDebtors': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewDebtors,
                    request_deserializer=issue__pb2.ViewDebtorsRequest.FromString,
                    response_serializer=issue__pb2.ViewDebtorsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'issue.IssueService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('issue.IssueService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IssueService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IssueBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/issue.IssueService/IssueBook',
            issue__pb2.IssueRequest.SerializeToString,
            issue__pb2.IssueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/issue.IssueService/CheckAvailability',
            issue__pb2.CheckAvailabilityRequest.SerializeToString,
            issue__pb2.CheckAvailabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReturnBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/issue.IssueService/ReturnBook',
            issue__pb2.ReturnRequest.SerializeToString,
            issue__pb2.ReturnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportLost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/issue.IssueService/ReportLost',
            issue__pb2.ReportLostRequest.SerializeToString,
            issue__pb2.ReportLostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllDebts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/issue.IssueService/GetAllDebts',
            issue__pb2.GetAllDebtsRequest.SerializeToString,
            issue__pb2.GetAllDebtsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewDebtors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/issue.IssueService/ViewDebtors',
            issue__pb2.ViewDebtorsRequest.SerializeToString,
            issue__pb2.ViewDebtorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
